// Code generated by accessory; DO NOT EDIT.

package models

import (
	"time"
)

func (restaurant *Restaurant) RestaurantId() string {
	if restaurant == nil {
		return ""
	}
	return restaurant.restaurantId
}

func (restaurant *Restaurant) Cuisine() Cuisine {
	if restaurant == nil {
		return 0
	}
	return restaurant.cuisine
}

func (restaurant *Restaurant) CostBracket() int {
	if restaurant == nil {
		return 0
	}
	return restaurant.costBracket
}

func (restaurant *Restaurant) Rating() float64 {
	if restaurant == nil {
		return 0
	}
	return restaurant.rating
}

func (restaurant *Restaurant) IsRecommended() bool {
	if restaurant == nil {
		return false
	}
	return restaurant.isRecommended
}

func (restaurant *Restaurant) OnboardedTime() time.Time {
	if restaurant == nil {
		return time.Time{}
	}
	return restaurant.onboardedTime
}
